sonar.projectKey=thebdag_EOM
sonar.organization=thebdag

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=EOM
#sonar.projectVersion=1.0

# Sources and Tests
sonar.sources=lib
sonar.tests=test

# Exclusions
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,lib/generated_plugin_registrant.dart
sonar.test.inclusions=test/**

# Coverage report path
sonar.dart.lcov.reportPaths=coverage/lcov.info

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
